### ISSUE TITLE
Query on "Information Security & Uses" file

### ISSUE THREAD

**Issue by Ambg05** [DinisCruz/Book_Software_Quality#178]
Query on the second last paragraph:

"So, the bottom line is that InfoSec tends to sometimes have a bad attitude toward the users and also the same thing sometimes happens in AppSec, the **sec guys having the same issue with the program as in developers where codes them, strikes off the code they are writing and basically really in a way it is offensive by to what developers are producing.**"

 I am not sure if you mean that the Sec guys strike off the code, and this is offensive to the developers. Can you clarify please? Thanks.

**Comment by DinisCruz** [comment]
I mean that the AppSec guys talk in a derogative way (i.e. offensive) of what developers create. It's very easy to complain about bad code and 'stupid' decisions, when one doesn't have the pressures and deadlines that the devs have
