### ISSUE TITLE
Question on #220 Measuring companies' AppSec

### ISSUE THREAD

**Issue by Ambg05** [DinisCruz/Book_Software_Quality#221]
Ref: [ https://github.com/DinisCruz/Book_Software_Quality/pull/220]

Thanks for your comments and changes to this chapter.

I just want to check I have understood the following sentence properly, on line 21: "There is still a huge amount of cost in moving away from that scalable platform to what I call the 'logging index' that we will be tracking."  Am I correct to call it a "logging index" , and am I correct to say "We will be tracking", and not  'that tracks all activity'. (url)

Thanks.

**Comment by DinisCruz** [comment]
It actually should be 'locking index' as in 'lock-in the customer into the software'

Also the ### only need to appear at the begining of the title
