### ISSUE TITLE
Question re: #226 Using Micro services as proxies

### ISSUE THREAD

**Issue by Ambg05** [DinisCruz/Book_Software_Quality#227]
[https://github.com/DinisCruz/Book_Software_Quality/pull/226/files]

I just want to check that my understanding is correct in this paragraph:
L 13: "The power of this workflow is that because you now have the unit test that locks the micro web service, you could move that new functionality to the micro service, and leave the main one online. This means that you allow the main web service to be conservative in making changes and sustainability. This supports robustness, consolidation, and re-factoring. Knowing that the clients are the micro web services, there is a very tight relationship between them which can secure, queue, and perform all sorts of tests before it reaches the client."

**Comment by DinisCruz** [comment]
yeah looks good (I will make a couple further changes when I merge it into the main text)
